import sys

sys.stdout.write("USER jasleen\r\n")
print("Command ok")
sys.stdout.write("uSeR jasleen\r\n")
print("Command ok")
sys.stdout.write("usr jasleen\r\n")
print("ERROR -- command")
sys.stdout.write("USERjasleen\r\n")
print("ERROR -- command")
sys.stdout.write("user\r\n")
print("ERROR -- command")
sys.stdout.write("USER jasl*n\r\n")
print("Command ok")
sys.stdout.write("USER jaslee\u00a5\r\n")
print("ERROR -- username")
sys.stdout.write("USER           jasleen\r\n")
print("Command ok")
sys.stdout.write("USER ja sl een \r\n")
print("Command ok")
sys.stdout.write("PASS 12@456\r\n")
print("Command ok")
sys.stdout.write("PASS 12*456\r\n")
print("Command ok")
sys.stdout.write("TYPE A\r\n")
print("Command ok")
sys.stdout.write("TYPE I\r\n")
print("Command ok")
sys.stdout.write("TYPE B\r\n")
print("ERROR -- type-code")
sys.stdout.write("SYST\r\n")
print("Command ok")
sys.stdout.write("SYST jasleen\r\n") 
print("ERROR -- CRLF")
sys.stdout.write("NOOP\r\n") 
print("Command ok")
sys.stdout.write("NOP\r\n") 
print("ERROR -- command")
sys.stdout.write("QUIT\r\n") 
print("Command ok")
sys.stdout.write("quit\r\n") 
print("Command ok")
sys.stdout.write("quit \r\n") 
print("ERROR -- CRLF")
